### ISSUE TITLE
Some feature request

### ISSUE THREAD

**Issue by xpader** [SmarterTomato/locate-this-document#1]
Could you please add some feature of this:

- Add option to set icons display in sidebar explorer or tab area (I hope that no icons to take up the tab area space).
- Hide open in file explorer in vscode remote mode (open in file explorer not work with remote mode).

**Comment by tzhaostraxcorp** [comment]
Sure, I will add that into next release (maybe the end of this week)

**Comment by tommywkzhao** [comment]
Hi, the latest version is out, and will have following options
![image](https://user-images.githubusercontent.com/11320441/123017914-e87cf280-d410-11eb-8100-036f17bf3de4.png)

For the second issue, the vscode remote mode. I don't have any experience on that, and don't have the resource to test it out. However, I did go through the documentation and add `!virtualWorkspace`. That should resolve the issue. Please try it out and let me know if it is working. Thanks

**Comment by xpader** [comment]
So fast! Thank you.
I'll test these and give you feedback when I get the update.

**Comment by xpader** [comment]
I found that there is some discussion about control tab area icon visibility https://github.com/microsoft/vscode/issues/46403
And I like https://github.com/microsoft/vscode/issues/46403#issuecomment-472642154, https://github.com/microsoft/vscode/issues/46403#issuecomment-505035757
May be we don't need anymore option about this when vscode implement that.

**Comment by tommywkzhao** [comment]
I love that feature as well. It will be great if they come up with a native solution. I want to remove some of the other icons as well but it is too complicated to go through every extension.
Have fun coding. Let me know if you have any other suggestions

**Comment by xpader** [comment]
Hi @tommywkzhao , I have test the release 1.1.1, options work but "Open in File Explorer" still show in vscode remote mode.

![Snipaste_2021-06-23_09-53-05](https://user-images.githubusercontent.com/8629617/123022894-13fbdf00-d409-11eb-9cdc-843cb3ec83d8.png)

**Comment by tommywkzhao** [comment]
Emm. Just one question, could you set workspace-specific settings for the remote project? If you can, you can set that to `ShowExplorerIcon` to `false` for this project only. Sorry for the inconvenience
![image](https://user-images.githubusercontent.com/11320441/123023454-be303280-d41a-11eb-8357-6e5163508efb.png)

**Comment by xpader** [comment]
Yes, but I just want hide Open In File Explorer buttons, not Locate button.

**Comment by tommywkzhao** [comment]
Sure, let me see if I can do anything about that. Will come back to you

**Comment by xpader** [comment]
I have found only one way to check if it's remote mode, but look like not a good way..

![Snipaste_2021-06-23_10-35-43](https://user-images.githubusercontent.com/8629617/123026490-dbf79a80-d40e-11eb-8460-b0b34ca27abf.png)

**Comment by xpader** [comment]
And I think the buttons need show when `isFileSystemResource`, because sometimes we open the extension tab or other resources.

And may be can check `resourceScheme` is 'file', may be remote mode not 'file', is 'ssh', 'wsl' or other.

![Snipaste_2021-06-23_10-47-27](https://user-images.githubusercontent.com/8629617/123027738-ef0b6a00-d410-11eb-8873-037af0d5e9bf.png)

**Comment by tommywkzhao** [comment]
Hi, I tried all the possible clause but still not working. I will add few more options to allow you switch off the icons separately

![image](https://user-images.githubusercontent.com/11320441/123036356-508f0100-d430-11eb-9c87-22f84db7b4d1.png)

**Comment by tommywkzhao** [comment]
Hi there, I have updated the latest version of v1.1.2. You can config individual icons in the configuration see below. Let me know if anything else. 

![image](https://user-images.githubusercontent.com/11320441/123039183-03f9f480-d435-11eb-98e3-b86f6d006d6c.png)

**Comment by xpader** [comment]
I have clone the code and test, I think I found the way.
For Locate icon, need add `isFileSystemResource` to sure current open tab is a file, and can locate to show the button.

`isFileSystemRecource` is true when current open tab is file whether in local or remote mode.

For Open in File Explorer, need add `resourceSchema == file` to sure current open tab is a local file schema, when in remote mode, resourceSchema value is like `remote-ssh`.

**Comment by xpader** [comment]
In my case, the menus section like this:
```
    "menus": {
      "editor/title": [
        {
          "command": "locateThisDocument.locateActiveDocument",
          "when": "config.locateThisDocument.showEditorTitleIcons && isFileSystemResource",
          "group": "navigation@1"
        },
        {
          "command": "locateThisDocument.openActiveDocumentInFileExplorer",
          "when": "config.locateThisDocument.showEditorTitleIcons && resourceSchema == file",
          "group": "navigation@2"
        }
      ],
      "view/title": [
        {
          "command": "locateThisDocument.locateActiveDocument",
          "group": "navigation",
          "when": "view == workbench.explorer.fileView && isFileSystemResource && config.locateThisDocument.showExplorerIcons"
        },
        {
          "command": "locateThisDocument.openActiveDocumentInFileExplorer",
          "group": "navigation",
          "when": "view == workbench.explorer.fileView && resourceSchema == file && config.locateThisDocument.showExplorerIcons"
        },
        {
          "command": "locateThisDocument.openWorkspaceRootFolderInFileExplorer",
          "group": "navigation",
          "when": "view == workbench.explorer.fileView && workspaceFolderCount == 1 && resourceSchema == file && config.locateThisDocument.showExplorerIcons"
        }
      ],
      "editor/title/context": [
        {
          "command": "locateThisDocument.locateThisDocument",
          "when": "config.locateThisDocument.showEditorTitleContext && isFileSystemResource",
          "group": "navigation"
        }
      ]
    }
```

And it's work.

**Comment by tommywkzhao** [comment]
I will add that no problem

**Comment by tommywkzhao** [comment]
I have updated the package v1.1.3, could you check if it works correctly for you? Thanks for the help

**Comment by xpader** [comment]
It is strange, editor title is work now, but explorer  title not, the `resourceScheme` is "vscode-remote" now, but the buttons in explorer sidebar still show.

![Snipaste_2021-06-23_14-59-01](https://user-images.githubusercontent.com/8629617/123050861-ba5cda00-d433-11eb-9fdf-9bd524b0db06.png)

**Comment by xpader** [comment]
You can check the context like this:

![动画](https://user-images.githubusercontent.com/8629617/123051841-baa9a500-d434-11eb-943f-9e0ae7ece66a.gif)

**Comment by tommywkzhao** [comment]
Could you use the configuration for now? I have a look tomorrow

**Comment by xpader** [comment]
Sure yes.

**Comment by tommywkzhao** [comment]
Good news, I found how to make that happen. Instead `resourceScheme == file`, I can use `remoteName == ''`. That will work. The new version has been released. Have a look if it works for you

![image](https://user-images.githubusercontent.com/11320441/123192867-146aa780-d4e7-11eb-8fe4-3e097cf44be8.png)

**Comment by xpader** [comment]
It's work perfect now.
Thank you.
